# by CDC
######### only need in windows #######
#[shell] 
#program = "wsl"			# '-d <Distro>' to specifie the distro
#args    = ["~"]
######################################

[window]
decorations	  = "full"	# none
title		      = "CDC"
dynamic_title	= false

[font]
size		    = 14
normal		  = { family = "Maple Mono" }
bold		    = { family = "Maple Mono" }
italic		  = { family = "Maple Mono" }
bold_italic	= { family = "Maple Mono" }

########## Gruvbox dark #############
[colors]
[colors.primary]
background  =  "#1d2021"
foreground  =  "#ebdbb2"

[colors.normal]
black       =  "#282828"
red         =  "#cc241d"
green       =  "#98971a"
yellow      =  "#d79921"
blue        =  "#458588"
magenta     =  "#b16286"
cyan        =  "#689d6a"
white       =  "#a89984"

[colors.bright]
black       =  "#928374"
red         =  "#fb4934"
green       =  "#b8bb26"
yellow      =  "#fabd2f"
blue        =  "#83a598"
magenta     =  "#d3869b"
cyan        =  "#8ec07c"
white       =  "#ebdbb2"
#################################
